"""3D LUT (.cube) generator and presets for video color grading.

Produces standard 33x33x33 .cube files compatible with FFmpeg lut3d,
DaVinci Resolve, Premiere Pro, and Final Cut Pro.
"""

from __future__ import annotations

import math
from pathlib import Path
from typing import Callable

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
LUTS_DIR = REPO_ROOT / "luts"


def clamp(val: float, low: float = 0.0, high: float = 1.0) -> float:
    return max(low, min(high, val))


def rgb_to_hsv(r: float, g: float, b: float) -> tuple[float, float, float]:
    max_c = max(r, g, b)
    min_c = min(r, g, b)
    diff = max_c - min_c

    # Value
    v = max_c

    # Saturation
    s = 0.0 if max_c == 0.0 else diff / max_c

    # Hue
    if diff == 0.0:
        h = 0.0
    elif max_c == r:
        h = (60.0 * ((g - b) / diff) + 360.0) % 360.0
    elif max_c == g:
        h = (60.0 * ((b - r) / diff) + 120.0) % 360.0
    else:
        h = (60.0 * ((r - g) / diff) + 240.0) % 360.0

    return h, s, v


def hsv_to_rgb(h: float, s: float, v: float) -> tuple[float, float, float]:
    h = h % 360.0
    c = v * s
    x = c * (1.0 - abs((h / 60.0) % 2.0 - 1.0))
    m = v - c

    if 0.0 <= h < 60.0:
        r1, g1, b1 = c, x, 0.0
    elif 60.0 <= h < 120.0:
        r1, g1, b1 = x, c, 0.0
    elif 120.0 <= h < 180.0:
        r1, g1, b1 = 0.0, c, x
    elif 180.0 <= h < 240.0:
        r1, g1, b1 = 0.0, x, c
    elif 240.0 <= h < 300.0:
        r1, g1, b1 = x, 0.0, c
    else:
        r1, g1, b1 = c, 0.0, x

    return r1 + m, g1 + m, b1 + m


def generate_cube(title: str, transform_fn: Callable[[float, float, float], tuple[float, float, float]],
                  size: int = 33) -> str:
    """Generate .cube ASCII representation using the standard loop order."""
    lines = [
        f'# Generated by OpenMontage LUT Generator',
        f'TITLE "{title}"',
        f'LUT_3D_SIZE {size}',
        'DOMAIN_MIN 0.0 0.0 0.0',
        'DOMAIN_MAX 1.0 1.0 1.0',
    ]
    for b_idx in range(size):
        for g_idx in range(size):
            for r_idx in range(size):
                r = r_idx / (size - 1)
                g = g_idx / (size - 1)
                b = b_idx / (size - 1)
                ro, go, bo = transform_fn(r, g, b)
                lines.append(f"{clamp(ro):.6f} {clamp(go):.6f} {clamp(bo):.6f}")
    return "\n".join(lines) + "\n"


# --- Transform Functions for Curated Looks ---

def transform_clean_bright(r: float, g: float, b: float) -> tuple[float, float, float]:
    """Clean, bright studio look with reduced yellow sallow tones and healthy skin vibrance."""
    # 1. Gentle gamma lift on shadows/midtones (exponent < 1.0 brightens)
    r_lift = math.pow(r, 0.90)
    g_lift = math.pow(g, 0.92)
    b_lift = math.pow(b, 0.88)

    h, s, v = rgb_to_hsv(r_lift, g_lift, b_lift)

    # In skin tone hue range (orange-yellow ~ 25° - 55°):
    # reduce yellow cast, nudge slightly towards peach/rose (~ 15° - 25°)
    if 20.0 <= h <= 65.0 and s > 0.08:
        # Shift hue slightly toward peach/red
        shift = (60.0 - h) / 40.0
        h_new = max(18.0, h - shift * 3.5)
        # Moderate saturation so it doesn't look orange
        s_new = s * 0.92
        # Slight boost to skin luminosity
        v_new = clamp(v * 1.05)
        r_out, g_out, b_out = hsv_to_rgb(h_new, s_new, v_new)
    else:
        # Vibrant highlights
        r_out, g_out, b_out = r_lift, g_lift, b_lift

    # Slight contrast curve: toe lift, soft shoulder
    return clamp(r_out), clamp(g_out), clamp(b_out)


def transform_warm_studio(r: float, g: float, b: float) -> tuple[float, float, float]:
    """Warm, inviting studio look with rich skin tones and soft contrast."""
    r_lift = math.pow(r, 0.92) * 1.02
    g_lift = math.pow(g, 0.95) * 1.00
    b_lift = math.pow(b, 0.98) * 0.96

    h, s, v = rgb_to_hsv(r_lift, g_lift, b_lift)
    if 15.0 <= h <= 55.0 and s > 0.05:
        s_new = clamp(s * 1.05)
        v_new = clamp(v * 1.03)
        return hsv_to_rgb(h, s_new, v_new)
    return clamp(r_lift), clamp(g_lift), clamp(b_lift)


def transform_cinematic_teal_orange(r: float, g: float, b: float) -> tuple[float, float, float]:
    """Modern cinematic look: subtle cool shadows (teal) with warm skin tones."""
    luma = 0.299 * r + 0.587 * g + 0.114 * b

    # Shadows get cool tint (cyan/teal), highlights stay neutral-warm
    shadow_weight = math.pow(max(0.0, 1.0 - luma), 2.0) * 0.06
    r_adj = r - shadow_weight * 0.5
    g_adj = g + shadow_weight * 0.3
    b_adj = b + shadow_weight * 0.8

    h, s, v = rgb_to_hsv(r_adj, g_adj, b_adj)
    # Protect and pop skin tones (h between 15° and 45°)
    if 15.0 <= h <= 50.0 and s > 0.08:
        s_new = clamp(s * 1.08)
        v_new = clamp(v * 1.02)
        r_adj, g_adj, b_adj = hsv_to_rgb(h, s_new, v_new)

    return clamp(r_adj), clamp(g_adj), clamp(b_adj)


def build_curated_luts(out_dir: Path | None = None) -> list[Path]:
    target_dir = out_dir or LUTS_DIR
    target_dir.mkdir(parents=True, exist_ok=True)

    definitions = [
        ("clean_bright.cube", "Clean & Bright", transform_clean_bright),
        ("warm_studio.cube", "Warm Studio", transform_warm_studio),
        ("cinematic_teal_orange.cube", "Cinematic Teal & Orange", transform_cinematic_teal_orange),
    ]

    generated = []
    for filename, title, fn in definitions:
        cube_path = target_dir / filename
        content = generate_cube(title, fn, size=33)
        cube_path.write_text(content, encoding="utf-8")
        generated.append(cube_path)

    return generated


if __name__ == "__main__":
    paths = build_curated_luts()
    for p in paths:
        print(f"Created: {p} ({p.stat().st_size / 1024:.1f} KB)")
